SRC_ROOT=${BUILD_ROOT}/kernel
OBJ_ROOT=${BUILD_ROOT}/obj
BUILD_DIR=${BUILD_ROOT}/config
CC_PREFIX=aarch64-none-elf
CC=${CC_PREFIX}-gcc
AS=${CC_PREFIX}-as
OC=${CC_PREFIX}-objcopy
C_FLAGS=-Wall -ffreestanding -nostdlib -nostartfiles -pedantic -mgeneral-regs-only 
L_FLAGS=-lgcc
